package main

import (
	"fmt"
	"strings"
)

const (
	ERR_AUTH_UNAUTHORIZED = 1 << iota
	ERR_AUTH_PROFILE_CHANGED
	ERR_ACCESS_USER
	ERR_INVALID_GRANT
	ERR_ENTITY_DELETED_PERMANENTLY
	ERR_ENTITY_NOT_FOUND
	ERR_ENTITY_DELETED
	ERR_ENTITY_PARENT_FOLDER_DELETED
	ERR_REQUEST_METHOD_NOT_ALLOWED
	ERR_INTERNAL_SERVER_ERROR
	ERR_ENTITY_EXISTS
	ERR_ENTITY_ROLE_IS_ASSIGNED
	UNAVAILABLE
	SERVICE_UNAVAILABLE
)

const (
	TOKEN_ERR = ERR_AUTH_PROFILE_CHANGED | ERR_INVALID_GRANT | ERR_AUTH_UNAUTHORIZED
)

type APIError struct {
	flag    int64
	message []string
}

// Add a kiteworks error to APIError
func (e *APIError) AddKWError(code, message string) {
	code = strings.ToUpper(code)

	switch code {
	case "ERR_ENTITY_ROLE_IS_ASSIGNED":
		e.flag |= ERR_ENTITY_ROLE_IS_ASSIGNED
	case "ERR_ENTITY_EXISTS":
		e.flag |= ERR_ENTITY_EXISTS
	case "ERR_AUTH_UNAUTHORIZED":
		e.flag |= ERR_AUTH_UNAUTHORIZED
	case "unauthorized_client":
		e.flag |= ERR_AUTH_UNAUTHORIZED
	case "ERR_AUTH_PROFILE_CHANGED":
		e.flag |= ERR_AUTH_PROFILE_CHANGED
	case "ERR_ACCESS_USER":
		e.flag |= ERR_ACCESS_USER
	case "invalid_grant":
		e.flag |= ERR_INVALID_GRANT
	case "ERR_ENTITY_DELETED_PERMANENTLY":
		e.flag |= ERR_ENTITY_DELETED_PERMANENTLY
	case "ERR_ENTITY_DELETED":
		e.flag |= ERR_ENTITY_DELETED
	case "ERR_ENTITY_NOT_FOUND":
		e.flag |= ERR_ENTITY_NOT_FOUND
	case "ERR_ENTITY_PARENT_FOLDER_DELETED":
		e.flag |= ERR_ENTITY_PARENT_FOLDER_DELETED
	case "ERR_REQUEST_METHOD_NOT_ALLOWED":
		e.flag |= ERR_REQUEST_METHOD_NOT_ALLOWED
	case "UNAVAILABLE":
		e.flag |= UNAVAILABLE
	default:
		if strings.Contains(code, "ERR_INTERNAL_") {
			e.flag |= ERR_INTERNAL_SERVER_ERROR
		}
	}
	e.message = append(e.message, fmt.Sprintf("%s. (%s)", message, code))
}

// Returns Error String.
func (e APIError) Error() string {
	str := make([]string, 0)
	e_len := len(e.message)
	for i := 0; i < e_len; i++ {
		if e_len == 1 {
			return e.message[i]
		} else {
			str = append(str, fmt.Sprintf("[%d] %s\n", i, e.message[i]))
		}
	}
	return strings.Join(str, "\n")
}

// Check for specific error code.
func RestError(err error, input int64) bool {
	if e, ok := err.(*APIError); !ok {
		return false
	} else {
		if e.flag&input != 0 {
			return true
		}
	}
	return false
}

// Return true if error was generated by REST call.
func IsRestError(err error) bool {
	if _, ok := err.(*APIError); ok {
		return true
	}
	return false
}

// Create a new REST error.
func NewRestError() *APIError {
	e := new(APIError)
	e.message = make([]string, 0)
	return e
}
